### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [2]:
import numpy as np

In [3]:
# Criando a lista
lista = [num for num in range(20)]

# Convertendo a lista em um array
array = np.array(lista)
matrix = array.reshape((4, 5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
# entendendo list comprehension
lista = []
for num in range(11):
    if num % 2 == 0:
        lista.append(num * num)
        
print(lista)

quadrados = [num * num for num in range(11) if num % 2 ==0]
print(quadrados)



[0, 4, 16, 36, 64, 100]
[0, 4, 16, 36, 64, 100]


### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [5]:
# Utilizando list comprehension
array = np.array([np.random.randint(0,21) for i in range(30)])

matriz_A = array.reshape((5, 6))
print(matriz_A)

[[ 7 17 13  2  0 10]
 [ 8 20 15  5 12 10]
 [11  5 16  7 16 13]
 [ 5 11  2  7  2  3]
 [17  4 11  0  2 10]]


In [6]:
# Refatorado
array = np.random.randint(0, 20, size=30)
matriz_A = array.reshape((5,6))
print(matriz_A)


[[ 6 14  6 14  4  7]
 [15  6 18 12 15 16]
 [ 0  0  0 13 15  0]
 [14  3 12 18 19  0]
 [17  0 15  5  6  0]]


In [7]:
matriz = np.random.randint(0, 20, size=30).reshape((5,6))
print(matriz)

[[ 5  3  7 13  9 18]
 [ 4 14 13 17  1 13]
 [19 16  1  3  8 17]
 [12  9  7  1  9 19]
 [ 4  5  3 19  8  6]]


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [8]:
primeira = matriz[[0, 1, 3],:]
print(primeira)
print()

segunda = matriz[[1, 2], :][:,[0, 2, 4]]
print(segunda)
print()

terceira = matriz[[1, 2], :][:,[1, 3]]

print(terceira)
print()

[[ 5  3  7 13  9 18]
 [ 4 14 13 17  1 13]
 [12  9  7  1  9 19]]

[[ 4 13  1]
 [19  1  8]]

[[14 17]
 [16  3]]



### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [14]:
# Instânciando o array com numpy
a = np.random.randint(0, 20, size=30).reshape((5, 6))
a

array([[ 0,  7,  2,  6, 19,  2],
       [17,  7,  2,  7,  8, 14],
       [17, 13,  6, 12,  8,  1],
       [11, 18,  6,  4, 11, 13],
       [13, 16, 10,  4,  4, 15]])

In [16]:
# copiando o array 'a' para o array 'ac'.
ac = a.copy()
ac

array([[ 0,  7,  2,  6, 19,  2],
       [17,  7,  2,  7,  8, 14],
       [17, 13,  6, 12,  8,  1],
       [11, 18,  6,  4, 11, 13],
       [13, 16, 10,  4,  4, 15]])

In [17]:
# - Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 

a[a > 10] = -1
a

array([[ 0,  7,  2,  6, -1,  2],
       [-1,  7,  2,  7,  8, -1],
       [-1, -1,  6, -1,  8,  1],
       [-1, -1,  6,  4, -1, -1],
       [-1, -1, 10,  4,  4, -1]])

In [18]:
#- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1

ac[(ac > 7) & (ac < 15)] = -1
ac

array([[ 0,  7,  2,  6, 19,  2],
       [17,  7,  2,  7, -1, -1],
       [17, -1,  6, -1, -1,  1],
       [-1, 18,  6,  4, -1, -1],
       [-1, 16, -1,  4,  4, 15]])

### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [20]:
a = np.arange(1, 201).reshape((20, 10))
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [23]:
# - Crie uma view de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
a_lpares = a[::2]
a_lpares



array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190]])

In [29]:
#- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

a_lpares_cimpares = a[::2, 1::2]
a_lpares_cimpares

array([[  2,   4,   6,   8,  10],
       [ 22,  24,  26,  28,  30],
       [ 42,  44,  46,  48,  50],
       [ 62,  64,  66,  68,  70],
       [ 82,  84,  86,  88,  90],
       [102, 104, 106, 108, 110],
       [122, 124, 126, 128, 130],
       [142, 144, 146, 148, 150],
       [162, 164, 166, 168, 170],
       [182, 184, 186, 188, 190]])

### Exercício 6)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [41]:
#TODO: refazer
copia = a.copy()
copia[::2, ::2] = -1
copia


array([[ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ -1,  22,  -1,  24,  -1,  26,  -1,  28,  -1,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ -1,  42,  -1,  44,  -1,  46,  -1,  48,  -1,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ -1,  62,  -1,  64,  -1,  66,  -1,  68,  -1,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ -1,  82,  -1,  84,  -1,  86,  -1,  88,  -1,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ -1, 102,  -1, 104,  -1, 106,  -1, 108,  -1, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [ -1, 122,  -1, 124,  -1, 126,  -1, 128,  -1, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [ -1, 142,  -1, 144,  -1, 146,  -1, 148,  -1, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [ -1, 162,  -1, 164,  -1, 166,  -1, 168,  -1, 170

### Exercício 7)
Construa uma função chamada `ordena_linhas` que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:
```python
A = np.array([[20, 26, 12], 
              [8, 3, 26], 
              [3, 10, 4]])
print(ordena_linhas(A))
```
deve resultar em
```python
[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
```

In [46]:
array = np.array([[20, 26, 12], [8, 3, 26], [3, 10, 4]])
array

array([[20, 26, 12],
       [ 8,  3, 26],
       [ 3, 10,  4]])

In [58]:
ordem = np.argsort(array, axis=0)

In [59]:
array[ordem]

array([[[ 3, 10,  4],
        [ 8,  3, 26],
        [ 3, 10,  4]],

       [[ 8,  3, 26],
        [ 3, 10,  4],
        [20, 26, 12]],

       [[20, 26, 12],
        [20, 26, 12],
        [ 8,  3, 26]]])

In [62]:
indices = np.argsort(array[:, 0])
array[indices]

array([[ 3, 10,  4],
       [ 8,  3, 26],
       [20, 26, 12]])

In [63]:
def ordenaMatriz(array):
    indices = np.argsort(array[:, 0])
    return array[indices]

In [65]:
print(array)
print()
ordenaMatriz(array)

[[20 26 12]
 [ 8  3 26]
 [ 3 10  4]]



array([[ 3, 10,  4],
       [ 8,  3, 26],
       [20, 26, 12]])