### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [5]:
import numpy as np

In [14]:
# Criando a lista
lista = [num for num in range(20)]

# Convertendo a lista em um array
array = np.array(lista)
matrix = array.reshape((4, 5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
# entendendo list comprehension
lista = []
for num in range(11):
    if num % 2 == 0:
        lista.append(num * num)
        
print(lista)

quadrados = [num * num for num in range(11) if num % 2 ==0]
print(quadrados)



[0, 4, 16, 36, 64, 100]
[0, 4, 16, 36, 64, 100]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [78]:
# Utilizando list comprehension
array = np.array([np.random.randint(0,21) for i in range(30)])

matriz_A = array.reshape((5, 6))
print(matriz_A)

[[16  7  8  3 10  0]
 [10 19 13  5 15 16]
 [ 8 15 13 15 17 12]
 [13 10 20  3 15 12]
 [13  4  5 13 20  7]]


In [75]:
# Refatorado
array = np.random.randint(0, 20, size=30)
matriz_A = array.reshape((5,6))
print(matriz_A)


[[14 17 16 16  1 19]
 [14 19  0  0  3 17]
 [12 11 18  2 17 10]
 [ 6  0 17 12  7  2]
 [ 9 16  0 14 14 16]]


In [77]:
matriz = np.random.randint(0, 20, size=30).reshape((5,6))
print(matriz)

[[ 9 12  9  4  1  2]
 [17  3  2  5 18 17]
 [ 6 19 18  7  6  0]
 [16 12 16 15 16 10]
 [18  9 18 15 19 12]]


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [97]:
primeira = matriz[[0, 1, 3],:]
print(primeira)
print()

segunda = matriz[[1, 2], :][:,[0, 2, 4]]
print(segunda)
print()

terceira = matriz[[1, 2], :][:,[1, 3]]

print(terceira)
print()

[[ 9 12  9  4  1  2]
 [17  3  2  5 18 17]
 [16 12 16 15 16 10]]

[[17  2 18]
 [ 6 18  6]]

[[ 3  5]
 [19  7]]



### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.