# Numpay

 NumPy é uma biblioteca fundamental para a computação científica em Python. Ele oferece suporte para a criação e manipulação de arrays e matrizes multidimensionais, além de fornecer uma vasta coleção de funções matemáticas de alto nível para operar sobre esses arrays.

### Aqui estão alguns pontos principais sobre o NumPy:

* __Arrays N-dimensionais__: O NumPy permite criar arrays de qualquer dimensão, o que é muito útil para trabalhar com grandes conjuntos de dados.
* __Desempenho__: O núcleo do NumPy é escrito em C, o que proporciona uma grande velocidade de execução, combinando a flexibilidade do Python com a eficiência do código compilado1.
* __Funções Matemáticas__: Ele inclui funções para álgebra linear, transformadas de Fourier, geração de números aleatórios, entre outras2.
* __Interoperabilidade__: O NumPy pode ser integrado com outras bibliotecas e ferramentas de computação científica, como SciPy, pandas, e bibliotecas de aprendizado de máquina

### Pequena revisão sobre listas em Python:

Listas em python não são arrays.

Listas são estruturas iteréveis.

Os métodos da lista alteram o objeto lista

In [1]:
lista = [1, 2, 3, 4]
type(lista)

var = lista.append('a')
print(var)
lista

None


[1, 2, 3, 4, 'a']

In [2]:
lista_num1 = [1, 2, 3, 4]
lista_num2 = [5, 6, 7, 8]

Executar operação "Soma" entre duas listas em python, na verdade os "concatena".

Listas são estruturas Iteráveis.

Listas não são vetores.



In [3]:

soma_lista = lista_num1 + lista_num2
soma_lista #[1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]

Curiosidade: É possível multiplicar listas

Tem o mesmo efeito de uma concatenação

In [4]:
multiplicacao_listas = lista_num1 * 2
multiplicacao_listas

[1, 2, 3, 4, 1, 2, 3, 4]

## Arrays

A es trutura de dados base do __Numpy__ são os **arrays**.

### Importante
* Todos os elementos de um array devem ser do mesmo tipo.
* Os arrays viabilizam a realização eficiente de operações numéricas envolvendo grandes quantidades de dados, sendo muito mais eficiente que as listas.
* Cada dimensão de um array é chamada de eixo **(axis)**
* Os eixos são numerados a partir de **0 (zero)**.
* Os elementos sãoacessados utilizando colchetes **[]** (semelhante às listas).




### Importante:
Antes de começar a trabalhar com numpy, é importante saber que como ela não é built-in do python, pode ser necessário sua instalação via PIP. 

#### O que é o PIP:
O pip é o gerenciador de pacotes oficial do Python. Ele facilita a instalação, atualização e remoção de pacotes e bibliotecas Python, permitindo que você acesse e utilize uma vasta gama de ferramentas desenvolvidas pela comunidade.

*  **Linux**: Se em sua distro linux você não tiver o **pip** instalado você pode fazê-lo através do comando: 
```
$ sudo apt install python3-pip
```

### Instalando o numpy:
De preferência em um virtual environment (.venv) do seu projeto, execute o comando:

```
$ pip install numpy
```



## Convertendo Listas em Arrays

Para trabalhar com a biblioteca __numpy__, antes de tudo você precisa fazer o import da mesma.

```
import numpy as np 
```
a terminação (as np) informa ao python que nós apelidamos a biblioteca como np




In [5]:
import numpy as np  

# Criando um array com numpy
numeros = np.array([1, 2, 3, 4, 1, 2, 3, 4])
print(numeros)
numeros


[1 2 3 4 1 2 3 4]


array([1, 2, 3, 4, 1, 2, 3, 4])

In [6]:
import numpy as np

data = [1, 2, 3, 4, 5]

array_data = np.array(data)

array_data


array([1, 2, 3, 4, 5])

#### Criando arrays multidimensionais com listas aninhadas

In [7]:
lista_aninhada = [[1, 2, 3], [4, 5, 6]]

array_2d = np.array(lista_aninhada)

array_2d

array([[1, 2, 3],
       [4, 5, 6]])

### Convertendo lista de strings em arrays

Como foi informado anteriormente, arrays tem melhor desempenhos para se trabalhar com números, mas também é possível converter uma lista de strings em um array.


In [8]:
# Lista de string
frutas = ['banana', 'goiaba', 'uva', 'pera']

# converter em array

array_frutas = np.array(frutas)
print(array_frutas)
array_frutas

['banana' 'goiaba' 'uva' 'pera']


array(['banana', 'goiaba', 'uva', 'pera'], dtype='<U6')

**dtype='<U6'** significa que cada elemento do array é uma string Unicode com até 6 caracteres1

Como também foi visto anteriormente, a estrutura de um array deve ser apenas usada para elementos de um tipo único, mas se tentarmos transformar uma lista contendo números e strings em um array?

In [9]:
lista_mista = [1, 2, 'a', 'b']

array_lista_mista = np.array(lista_mista)
array_lista_mista

array(['1', '2', 'a', 'b'], dtype='<U21')

Quando fazemos isso, o python vai tentar converter todos os elementos para um mesmo tipo, nesse caso acima, todos foram transformados em **strig**.

Se tentar-mos converter uma listas de tipos numérico diferentes, o python tentará transformar todos os elementos em um único tipo.

In [10]:
lista_int_float = [1, 2, 3.0, 4.5, 5.2]

array_lista_int_float = np.array(lista_int_float)

array_lista_int_float

array([1. , 2. , 3. , 4.5, 5.2])

## Atributos da biblioteca Numpy

Com o nosso array_2d podemos ver alguns atributos da biblioteca numpy

#### ndim

O método ndim do NumPy é usado para determinar o número de dimensões (ou eixos) de um array. Ele é um atributo do objeto ndarray e retorna um valor inteiro que representa o número de dimensões do array.

In [11]:
numero_dimensoes = array_2d.ndim

print(f"O array tem {numero_dimensoes} dimensões.")

O array tem 2 dimensões.


#### Shape

O método shape do NumPy é um atributo do objeto ndarray que retorna uma tupla representando as dimensões do array. Ele é muito útil para entender a estrutura dos dados com os quais você está trabalhando.

In [12]:
dimensao, elementos = array_2d.shape
print(f"O array tem {dimensao} linhas e {elementos} colunas. ")

O array tem 2 linhas e 3 colunas. 


In [13]:
array_1d = np.array([1, 2, 3, 4])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.zeros((2, 3, 4))

# Usando o atributo shape
print(array_1d.shape)  # Saída: (4,)
print(array_2d.shape)  # Saída: (2, 3)
print(array_3d.shape)  # Saída: (2, 3, 4)

(4,)
(2, 3)
(2, 3, 4)


No exemplo acima:

array_1d.shape retorna (4,), indicando que é um array unidimensional com 4 elementos.

array_2d.shape retorna (2, 3), indicando que é um array bidimensional com 2 linhas e 3 colunas.

array_3d.shape retorna (2, 3, 4), indicando que é um array tridimensional com 2 blocos, 3 linhas e 4 colunas.

Além de obter a forma do array, você também pode usar o atributo shape para redimensionar o array, desde que o número total de elementos permaneça o mesmo

#### Size

Retorna o número total de elementos no array.

In [14]:
print(f'O array tem {array_3d.size} elementos')
array_3d

O array tem 24 elementos


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Dtype

Retorna o tipo de dados no array

In [15]:
print(f'Tipos de dados: {array_3d.dtype}')
array_3d

Tipos de dados: float64


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Itemsize
Retorna o tamanho (em bytes) de cada elemento no array

In [16]:
print(f'Cada elemento tem {array_data.itemsize} bytes')
array_data

Cada elemento tem 8 bytes


array([1, 2, 3, 4, 5])

#### Nbytes
Retorna o número total de bytes consumidos pelos elementos no array.

In [17]:
print(f'O array consome {array_data.nbytes} bytes')
array_data

O array consome 40 bytes


array([1, 2, 3, 4, 5])

#### T transposta
Retorna uma matriz transposta.



In [18]:
lista = [[1,2,3],[4,5,6]]
meu_array = np.array(lista)
print(f'Array Original\n{meu_array}\nTransposto: \n{meu_array.T}')

Array Original
[[1 2 3]
 [4 5 6]]
Transposto: 
[[1 4]
 [2 5]
 [3 6]]


In [19]:
lista2 = [[1,2,3],[4,5,6], [7,8,9]]
meu_array2 = np.array(lista2)
print(f'Array Original\n{meu_array2}\nTransposto: \n{meu_array2.T}')

Array Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposto: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Data
Retorna um buffer que aponta para o início de memória dos dados do array

In [20]:
print(meu_array2.data)

### Podemos criar arrays utilizando as funções **zeros** e **ones**.

A função **zeros** do numpy é usada para criar um novo array com forma e tipo especificados, preenchidos com zeros.

* SINTAXE
```
numpy.zeros(shape, dtype=float, order='C', *, like=None)
```
Onde:

* Shape: tipo int ou tuplas definem a forma do novo array.

* dtype: Opicional.

* Order: {‘C’, ‘F’}, opcional. Se deve armazenar dados multidimensionais em ordem row-major (estilo C) ou column-major (estilo Fortran) na memória. O padrão é ‘C’.

* like: array_like, opcional. Objeto de referência para permitir a criação de arrays que não são arrays do NumPy. Se um array-like passado como like suporta o protocolo __array_function__, o resultado será definido por ele.


In [21]:
# Zeros: Cria um array com todos os valores nulos
# É necessário passar o números de elementos queremos que o nosso array possua.

nulo = np.zeros(5)

nulo

array([0., 0., 0., 0., 0.])

In [22]:
# Criar um array multidimensional de zeros.
# É passados o número de as dimensões e o números de elementos como parâmetro na forma de uma tupla.

nulos_3d = np.zeros((3, 5))
nulos_3d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
ones_3d = np.ones((3, 5))
ones_3d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Arange

No python temos a função **range()** que nos permite gerar números, como por exemplo uma sequência de 0 a 10. Onde temos que passar como parâmetros (início, fim , passo)
onde o início é o começo da contagem, o fim é até onde vai a sequência -1, e o passo que é a diferença entre cada número da sequência. Apenas o parâmetro fim é obrigatório, sendo os outros dois opicionais. No casso do parâmtro passo, ele aceita apenas números do tipo inteiro, não sendo possível o utilização de número de pontos flutuante.

In [24]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [25]:
list(range(1, 10, 1.5))

TypeError: 'float' object cannot be interpreted as an integer

O **numpy** tem seu próprio método range, que é chamado de **arange**, que funciona semelhante ao range, com a diferença que este pode receber no seu parâmetro passo, números de ponto flutuante. 

In [40]:
np.arange(1,10, 1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

### Linspace

O Linspace é uma função específica do NumPy que gera números espaçados de forma uniforme em um intervalo especificado. Ele retorna um arranjo de valores igualmente espaçados dentro de um intervalo definido.

Sua sintaxe básica:
```
np.linspace(start, stop, num)
```
* start: O valor inicial do intervalo.
* stop: O valor final do intervalo.
* num: O número de valores a serem gerados.

In [19]:
# Gerando 10 valores igualmente espaçados entre 0 e 1.

arr_linspace = np.linspace(0, 1, 10)
print(arr_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

```
#### Parâmetros
* start: O valor inicial da sequência.
* stop: O valor final da sequência.
* num: Número de amostras a serem geradas (o padrão é 50).
* endpoint: Se True, stop é a última amostra; caso contrário, não é incluída (o padrão é True).
* retstep: Se True, retorna as amostras e o passo entre elas (o padrão é False).
* dtype: O tipo do array de saída (o padrão é inferido a partir de start e stop).
* axis: O eixo no resultado para armazenar as amostras (o padrão é 0).

In [20]:
# Excluindo endpoint
arr = np.linspace(1, 10, num=10, endpoint=False)
print(arr)
# Saída: [1. 1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [21]:
# Retornando o tamanho do passo

array, passo = np.linspace(0, 1, num=5, retstep=True)

print(f"Array: {array}\nPasso: {passo}")

Array: [0.   0.25 0.5  0.75 1.  ]
Passo: 0.25


##### Exemplos práticos de uso do linspace

* **Visualização de dados**: O Linspace é frequentemente utilizado para gerar valores espaçados que serão utilizados como eixos em gráficos. Por exemplo, ao criar um gráfico de linha, podemos definir o eixo x como um arranjo de valores igualmente espaçados usando o Linspace.

* **Cálculos Numéricos**: O Linspace também pode ser usado para realizar cálculos numéricos. Por exemplo, se quisermos calcular a soma de uma série de valores espaçados igualmente, podemos gerar esses valores usando o Linspace e, em seguida, utilizar a função de soma do NumPy para realizar o cálculo.

#### Construindo arrays com **combinações de arrays** entre eles:

Desde de que os arrays tenham a mesma quantidade de elementos, é possível realizar operações matemáticas entre eles.

In [29]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.ones(4)

arr3 = np.arange(5, 9)

soma = arr1 + arr2 + arr3
sub = arr1 - arr2 * arr3
mult = arr1 *  - arr3
div = arr1 / arr2 + arr3
pot = arr1 ** 2
print(f"Soma: {soma}\nSubtração: {sub}\nMultiplicação: {mult}\nDivisão: {div}")
pot

Soma: [ 7.  9. 11. 13.]
Subtração: [-4. -4. -4. -4.]
Multiplicação: [ -5 -12 -21 -32]
Divisão: [ 6.  8. 10. 12.]


array([ 1,  4,  9, 16])

### Random

Assim como a biblioteca random, o numpy tem seu próprio método de geração de números aleatórios:

In [36]:
numero = np.random.randint(0, 10)
numero

3

### random.normal
Essa é uma função especial do **Numpy** onde dado a quantidade de elementos, ela irá criar elementos de uma distribuição normal(**Gaussiana**):

In [37]:
np.random.normal(loc=0, scale=1, size=10)

array([ 0.3935261 , -1.026636  , -0.45427763,  0.79632935, -0.19108923,
        0.78525403, -2.87409676,  0.68735066,  0.54604223, -1.29613813])

## Tipos de dados em arrays

O tipo de dado, ou dtype, é uma informação de metadados, ou seja, são dados sobre os dados. Ele nos informa qual é o tipo de dado armazenado em memória.

In [42]:
# Criando um array e passando como dtype o tipo int

array_int = np.array([100, 200, 300], dtype=np.int32)

array_int

array([100, 200, 300], dtype=int32)

In [41]:
# Criando um array e passando como dtype o tipo float

array_float = np.array([1, 2, 3], dtype=np.float64)
array_float

array([1., 2., 3.])

### Curiosidade - Algebra Linear com Numpy

In [ ]:
#np.linalg.
# Produto interno, Produto escalar

In [42]:
# Matriz 2D
matriz = np.array([[1, 2, 3],[4, 5, 6]])

matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Matriz 3 x 3

lista = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matriz_3d = np.array(lista)
matriz_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# Informações da Matriz criada
print(f"Dimensão da matriz: {matriz.ndim}")
print(f"Shape da Matriz: {matriz.shape}")
print(f"Número de elementos da Matriz: {matriz.size}")
print(f"Tipo dos elementos da Matriz: {matriz.dtype}")
print(f"Tamanho em Bytes de cada elemento da Matriz: {matriz.itemsize}")
print(f"Local da menmória onde está alocado essa matriz: {matriz.data}")

Dimensão da matriz: 2
Shape da Matriz: (2, 3)
Número de elementos da Matriz: 6
Tipo dos elementos da Matriz: int64
Tamanho em Bytes de cada elemento da Matriz: 8
Local da menmória onde está alocado essa matriz: <memory at 0x7ffbb06b0ba0>


In [39]:
# Matriz 1D com 5 elementos
matriz1 = np.arange(6, 11)
# Matriz 1D com 5 elementos
matriz2 = np.array([1, 2, 3, 4, 5])
# Soma entre os elementos das matrizes: matriz1 + Matriz2
matriz3 = matriz1 + matriz2
# Subtração entre os elementos das matrizes: matriz1 + Matriz2
matriz4 = matriz1 - matriz2
# Multiplicação entre os elementos das matrizes: matriz1 + Matriz2
matriz5 = matriz1 * matriz2
# Divisão entre os elementos das matrizes: matriz1 + Matriz2
matriz6 = matriz1 / matriz2
print(f"Matriz1 : {matriz1}")
print(f"Matriz2 : {matriz2}")
print()
print(f"matriz1 + matriz2: {matriz3}")
print(f"matriz1 - matriz2: {matriz4}")
print(f"matriz1 * matriz2: {matriz5}")
print(f"matriz1 / matriz2: {matriz6}")

Matriz1 : [ 6  7  8  9 10]
Matriz2 : [1 2 3 4 5]

matriz1 + matriz2: [ 7  9 11 13 15]
matriz1 - matriz2: [5 5 5 5 5]
matriz1 * matriz2: [ 6 14 24 36 50]
matriz1 / matriz2: [6.         3.5        2.66666667 2.25       2.        ]


In [44]:
# Outros exemplos

lista_listas = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matriz_listas = np.array(lista_listas)
matriz_listas

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# Criando uma matriz de zeros

matriz_zeros = np.zeros((3,3))
matriz_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# Criando uma matriz de ums

matriz_ones = np.ones((3,8))
matriz_ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
# Shape

print(matriz_zeros.shape)
print(matriz_ones.itemsize)

(3, 3)
8


## Métodos Numpy
Métodos úteis para serem aplicados em arrays, muitos desses métodos são herdados pelo **Pandas**.


#### Reshape
Permite reformatar o array modificando o número de linhas e colunas, porém, a nova 'shape' tem que possuir o mesmo número de elementos do array original: 

In [40]:
# Criando um array de 9 elementos
arr1 = np.arange(1,10)
print(arr1)

# transformando ele em uma matriz - reshape
# tem que respeitar a quantidade
matriz_arr = arr1.reshape((3,3)) # tem que passar o formato

matriz_arr

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr1 = np.arange(1,13)
print(arr1)

# transformando ele em uma matriz - reshape
# tem que respeitar a quantidade
matriz_arr = arr1.reshape((3,4)) # tem que passar o formato

matriz_arr

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Flatten

É uilizado para transformar um array multidimensional em um array unidimensional. Retorna uma cópia do array original em uma única dimensão.

Ele pode receber um parâmetro 'order' (opcional) que especifica a ordem dos elementos no array achatado:

* "C": Achata em ordem row-major(estilo C).

* "F": Achata em ordem column-major (estilo Fortran).

* "A": Achata em ordem column-major se o array for contíguo em memória no estilo Fortran, ou row-major caso contrário.

* "K": Achata na ordem em que os elementos estão dispostos na memória.

In [48]:
lista= [[9,5,3],[1,8,4]]
arr2D = np.array(lista)
print(f"Formato Original\n{arr2D}\n")

arr_flatten_default = arr2D.flatten()
arr_flatten_c = arr2D.flatten("C")
arr_flatten_f = arr2D.flatten("F")
arr_flatten_a = arr2D.flatten("A")
arr_flatten_k = arr2D.flatten("K")

print("Default: ",arr_flatten_default)
print("C: ", arr_flatten_c)
print("F: ",arr_flatten_f)
print("A: ",arr_flatten_a)
print("K: ",arr_flatten_k)


Formato Original
[[9 5 3]
 [1 8 4]]

Default:  [9 5 3 1 8 4]
C:  [9 5 3 1 8 4]
F:  [9 1 5 8 3 4]
A:  [9 5 3 1 8 4]
K:  [9 5 3 1 8 4]


In [66]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
arr3D = np.array(lista)
arr3D

arr_flatten = arr3D.flatten()
print("Original\n", arr3D)
print("Achatado:\n ", arr_flatten)


Original
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Achatado:
  [1 2 3 4 5 6 7 8 9]


array([5, 2, 3, 4, 5, 6, 7, 8, 9])

#### Diferença entre **flatten** e **ravel**
* **flatten**: Retorna uma cópia do array achatado. Modificações no array resultante não afetam o array original.

* **ravel**: Retorna uma vista do array original sempre que possível. Modificações no array resultante podem afetar o array original.

#### Ravel
Concatena as linhas da matriz em um array unidimensional:


In [64]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
arr3D = np.array(lista)

a = arr3D.ravel()


array([50,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
# Exemplo da internet

# Criar um array 2D
a = np.array([[1, 2], [3, 4]])

# Achatar o array em ordem maior da linha (padrão)
b = a.flatten()
print(b)  # Saída: [1 2 3 4]

# Achatar o array em ordem maior da coluna
c = a.flatten(order='F')
print(c)  # Saída: [1 3 2 4]

[1 2 3 4]
[1 3 2 4]


In [73]:
# Entendendo as diferenças

# Vou atribuir um valor ao array b
b[0] = 1000

print(b)
print(a) # array a não foi alterado

#======================================
# Agora com ravel
c = a.ravel()
c[-1] = 555
print(c)
print()
print(a) # c foi alterado


[1000    2    3    4]
[[  1   2]
 [  3 555]]
[  1   2   3 555]

[[  1   2]
 [  3 555]]


#### **Transpose**

Transpõe um array (inverte linhas e colunas)

In [77]:
# Criando o array
arr = np.array([1,2,3,4,5,6,7,8,9])

# alterando sua forma
matriz = arr.reshape((3,3))

# invertendo linhas e colunas
transposta = matriz.transpose()
transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Métodos Matemáticos**

#### **SUM**

Calcula a soma dos elementos do array

In [79]:
soma = transposta.sum()
print(soma)

45


In [38]:
matriz = np.random.randint(1, 20, size=25).reshape((5, 5))
print(matriz)
soma = matriz.sum()
print("====== SOMA ======")
print(soma)


[[ 2 10 13  8 14]
 [ 3 13 14  8  1]
 [ 7  6 19 17 19]
 [ 2 12 17  9 19]
 [19  4 10  1 13]]
====== SOMA ======
260


#### **Mean**

Calcula a média dos elementos do array.

In [80]:
media = transposta.mean()
print(media)

5.0


In [45]:
matriz = np.random.randint(1, 100, size= 10).reshape((5,2))
print(matriz)
print("====== Media ======")
media = matriz.mean()
print(media)

[[92 23]
 [60 53]
 [ 3  8]
 [42 11]
 [18 95]]
====== Media ======
40.5


#### **Std**
Calcula o desvio padrão dos elementos do array.

In [81]:
desvio = transposta.std()
print(desvio)

2.581988897471611


In [63]:
matriz_aleatoria = np.random.randint(1, 100, size=50).reshape((5, 10))

print(matriz_aleatoria)

print("====== DESVIO PADRÃO ======")

dp = matriz_aleatoria.std().round(2)
print(dp)

[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
====== DESVIO PADRÃO ======
28.49


#### **Max**
Retorna o elemento de maior valor de um array:

In [64]:
print(matriz_aleatoria)
print("Maior item")
print(matriz_aleatoria.max())


[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
Maior item
93


#### **ArgMax**
Retorna o índice do elemento de maior valor do array:

In [66]:
print(matriz_aleatoria)
print("Índice do maior item")
print(matriz_aleatoria.argmax())

[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
Índice do maior item
27


#### **Min**
Retorna o elemento de menor valor do array:

In [67]:
print(matriz_aleatoria)
print("Elemento de menor valor")
print(matriz_aleatoria.min())

[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
Elemento de menor valor
1


#### **ArgMin**
Retorna o índice do elemento de menor valor do array

In [68]:
print(matriz_aleatoria)
print("Elemento de menor valor")
print(matriz_aleatoria.argmin())

[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
Elemento de menor valor
21


#### **Sort**

A função sort é usada para ordenar arrays em Numpy.

##### Sintaxe
```
np.sort(array, axis=-1, kind=None, order=None)
```

Onde:
* **array**: o array que eu vou ordenar

* **axis**: O eixo ao longo do qual ordenar. **Padrão -1**, que ordena ao longo do último eixo. Caso **None**, o array é achatatdo antes de ordenar.

* **kind**: Algoritmo de ordenação a ser utilizado. Podendo ser:
    * 'quicksort' (padrão)
    * 'mergesort'
    * 'heapsort'
    * 'stable'

* **order**: Quando **array** é um array com campos definidos, este argumento especifica quais campos comparar primeiro, segundo.

In [27]:
array = np.array([[3, 2, 1], [6, 5, 4]])
print(array)
ordenado = np.sort(array)
ordenado

[[3 2 1]
 [6 5 4]]


array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
ordenado_eixo_0 = np.sort(array, axis=0)
ordenado_eixo_0

array([[3, 2, 1],
       [6, 5, 4]])

#### **ArgSort**
A função __numpy.argsort__ é usada para obter os índices que ordenariam um array. Em outras palavras, ela retorna um array de índices que, se usados para indexar o array original, resultariam em um array ordenado.

In [69]:
print(matriz_aleatoria)
print("Ordem de valores")
print(matriz_aleatoria.argsort())

[[43 46 72 87 90 43  2 27  5 18]
 [58 43 38 51 29 40 31  4 86 76]
 [79  1 49 56 20 46 12 93 22 71]
 [93 42 20 46 58 82  3 78 31 26]
 [47 79 10 10  4 55 89 78 88 46]]
Ordem de valores
[[6 8 9 7 0 5 1 2 3 4]
 [7 4 6 2 5 1 3 0 9 8]
 [1 6 4 8 5 2 3 9 0 7]
 [6 2 9 8 1 3 4 7 5 0]
 [4 3 2 9 0 5 7 1 8 6]]


In [70]:
# Array original
x = np.array([3, 1, 2])

# Obter os índices que ordenariam o array
indices_ordenados = np.argsort(x)

print(indices_ordenados)

[1 2 0]


Neste exemplo, np.argsort(x) retorna [1, 2, 0], que são os índices que, se usados para indexar x, resultariam em um array ordenado: [x[1], x[2], x[0]] ou [1, 2, 3].

#### Aplicações em Arrays Multidimensionais
Você também pode usar argsort em arrays multidimensionais, especificando o eixo ao longo do qual deseja ordenar:

In [71]:
x = np.array([[0, 3], [2, 2]])

# Obter os índices que ordenariam o array ao longo do eixo 0 (linhas)
indices_ordenados = np.argsort(x, axis=0)

print(indices_ordenados)

[[0 1]
 [1 0]]


Neste caso, np.argsort(x, axis=0) retorna os índices que ordenariam o array ao longo das linhas.

-> Parâmetros Principais

**a**: Array a ser ordenado.
**axis**: Eixo ao longo do qual ordenar. O padrão é -1 (último eixo).

**kind**: Algoritmo de ordenação a ser usado ('quicksort', 'mergesort', 'heapsort', 'stable').

**order**: Quando a é um array com campos definidos, este argumento especifica quais campos comparar primeiro, segundo, etc.

In [72]:
# Array 2D
x = np.array([[0, 3], [2, 2]])

# Obter os índices que ordenariam o array ao longo do eixo 1 (colunas)
indices_ordenados = np.argsort(x, axis=1)

# Usar os índices para obter o array ordenado
array_ordenado = np.take_along_axis(x, indices_ordenados, axis=1)

print(array_ordenado)

[[0 3]
 [2 2]]


#### **Astype**
A função numpy.astype é usada para converter um array NumPy de um tipo de dado para outro. Isso é especialmente útil em pré-processamento de dados, onde garantir a consistência dos tipos de dados é crucial.

##### SINTAXE
```
array.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
```
 **Parâmetros**

**dtype**: O tipo de dado para o qual você deseja converter o array. Pode ser um tipo NumPy, como np.int32, np.float64, etc.

**order**: Controla a disposição da memória do array resultante. Pode ser 'C' (ordem C), 'F' (ordem Fortran), 'A' (ordem Fortran se todos os arrays forem contíguos em Fortran, caso contrário, ordem C) ou 'K' (o mais próximo possível da ordem dos elementos na memória).

**casting**: Controla o tipo de conversão de dados que pode ocorrer. Pode ser 'no', 'equiv', 'safe', 'same_kind' ou 'unsafe'.

**subok**: Se True, sub-classes serão passadas adiante; caso contrário, o array retornado será forçado a ser um array da classe base.

**copy**: Se True, sempre retorna um novo array. Se False e o dtype, order e subok forem satisfeitos, o array de entrada é retornado em vez de uma cópia.


In [73]:
# Array original
x = np.array([1.2, 2.5, 3.8])

# Converter para inteiros
x_int = x.astype(int)

print(x_int)

[1 2 3]


In [74]:
x = np.array([[1.5, 2.3], [3.1, 4.8]])

# Converter para inteiros
x_int = x.astype(np.int32)

print(x_int)

[[1 2]
 [3 4]]


#### **Dot**

Calcula o produto escalar de dois arrays.

Dependendo das dimensões dos arrays, o comportamento da função pode variar:

**Vetores 1D**: Se ambos os arrays forem vetores 1D, numpy.dot calcula o produto interno dos vetores.

**Matrizes 2D**: Se ambos os arrays forem matrizes 2D, numpy.dot realiza a multiplicação de matrizes.

**Escalares**: Se um dos arrays for um escalar (0D), numpy.dot realiza a multiplicação escalar.

**Arrays N-Dimensionais**: Para arrays N-dimensionais, numpy.dot realiza um produto soma sobre o último eixo do primeiro array e o penúltimo eixo do segundo array.


In [84]:
# vetores 1D
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
resultado = np.dot(a, b)
print(resultado)

32


In [87]:
# vetores 2D - Multiplicação de matrizes

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
resultado = np.dot(a, b)
print(resultado)
a, b

[[19 22]
 [43 50]]


(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [88]:
# Multiplicação Escalar

a = 3
b = np.array([1, 2, 3])
resultado = np.dot(a, b)
print(resultado)  # Saída: [3 6 9]

[3 6 9]


### **Métodos de Indexação e Fatiamento**

#### **Slice**
Permite acessar subarrays




In [102]:
transposta
resultado = transposta[0][2]
print(transposta)
print(resultado)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
7


#### **Where**
Retorna o índice dos elementos que satisfazem uma condição.

SINTAXE:
```
numpy.where(condition, [x, y])
```

* **Condition**: Um array de booleanos ou uma expressão que resulta em um array de booleanos.

* **x**: (Opcional) Valores a serem escolhidos onde a condição é verdadeira.

* **y**: (Opcional) Valores a serem escolhidos onde a condição é falsa.

##### Funcionamento

1. Sem x e y: Se apenas a condição for fornecida, numpy.where() retorna os índices dos elementos que satisfazem a condição.

2. Com x e y: Se x e y forem fornecidos, a função retorna um array onde cada elemento é escolhido de x ou y dependendo se a condição é verdadeira ou falsa.

In [104]:
maior_3 = np.where(transposta > 8)
print(maior_3)

(array([2]), array([2]))


In [105]:

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.where(a < 5)
print(indices)


(array([0, 1, 2, 3, 4]),)


In [108]:
# Aqui, numpy.where() retorna os índices dos elementos em a que são menores que 5.

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.where(a < 5, a, a * 10)
print(result)
result

[ 0  1  2  3  4 50 60 70 80 90]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [109]:
# Aqui, os elementos menores que 5 são mantidos, e os outros são substituídos por -1.

a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
result = np.where(a < 5, a, -1)
print(result)


[[ 0  1  2]
 [ 3  4 -1]
 [-1 -1 -1]]


### **Métodos de Ordenação**

#### **Sort**

Ordena os elementos do array

In [114]:
lista = [53, 2, 8, 23, 1, 31, 19]

array = np.array(lista)
print(array)

ordenada = np.sort(array)
print(ordenada)

[53  2  8 23  1 31 19]
[ 1  2  8 19 23 31 53]


### Métodos de entrada e Saída

#### Save
Salva um array em um arquivo binário



In [115]:
np.save('ordenado.npy', array)

#### Load

Carrega um array de um arquivo binário.

In [116]:
#Lendo um arquivo binário npy
dados = np.load('ordenado.npy')
dados

array([53,  2,  8, 23,  1, 31, 19])

### Máscara Booleana

Uma máscara booleana é um array de valores booleanos (True ou False) que correspondem a cada elemento de um array original. Esses valores indicam se o elemento correspondente deve ser incluído ou não em uma operação subsequente.

In [28]:
# Criando uma máscara booleana

# Estâncio o array numpy
array = np.array([1,2,-3,4,5,-6])

# crio uma variável 'mascara' atribuíndo a ela uma condição que será aplicada a cada elemento do array. Nesse caso, ele construirá um array de valores booleanos onde quando a condição for atendida ele atribuirá o booleano True na posição do elemento. 
mascara = array < 0
mascara

array([False, False,  True, False, False,  True])

In [30]:
# Se eu atribuir a uma nova variável o array original indexado pelo o array 'mascara', o numpy atribuirá a essa nova variável apenas os elementos cuja a condição seja True. 
outro_array = array[mascara]
outro_array

array([-3, -6])

In [31]:
# Também posso fazer dessa forma

terceiro_array = array[array < 0]
terceiro_array

array([-3, -6])

#### Modificando valores usando Máscara Booleana.

Também é possível usar máscaras booleanas para modificar elementos do array.

In [41]:
# Instânciando uma matriz 3 x 3

# Utilizei random.choice para gerar numeros não repetidos
matriz = np.random.choice(range(-10, 10), size=9, replace=False).reshape((3, 3))

# substituir todos os números negativos por 1

matriz[matriz < 0] = 1

matriz

array([[1, 8, 2],
       [4, 9, 3],
       [5, 1, 1]])

In [48]:
# Criando uma nova matriz para não alterar a original

# Random com choice para não repetir
matriz = np.random.choice(range(1, 100), size=12, replace=False).reshape((3, 4))
print(matriz)
print()

# copio a matriz para a nova variável que será alterada com o método copy.
copia = matriz.copy()

# Utilizo a máscara booleana para substituir os valores que atendem a minha condição
copia[matriz % 2 != 0] = 1

print(copia)

[[45 92 82 91]
 [60 21 93 19]
 [80 28 69 97]]

[[ 1 92 82  1]
 [60  1  1  1]
 [80 28  1  1]]


#### Aplicando condições compostas com Máscaras booleanas

É possível testar mais de uma condição em um mesmo comando usando máscaras booleanas no NumPy. Você pode combinar condições usando operadores lógicos: 
* **&** (e) 
* **|** (ou)
* **~** (not)

In [50]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Criando uma máscara booleana com duas condições
mascara = (array > 5) & (array < 9)

# Usando a máscara booleana para filtrar os elementos
resultado = array[mascara]

print(resultado)
# Saída: [6 7 8]

[6 7 8]


### **Fatiamento no Numpy**

O fatiamento em NumPy é uma técnica poderosa que permite selecionar sub-seções de um array para manipulação e análise de dados. Aqui estão os conceitos básicos:

#### **Fatiamento Básico**
O fatiamento em NumPy é semelhante ao fatiamento de listas em Python. Você usa a sintaxe 

```
start:stop:step
``` 
dentro de colchetes para definir o intervalo que deseja selecionar.

In [54]:
# Array Unidimensional

array = np.array([1,2,3,4,5])

print(array[1:3])
print(array[::2])
print(array[::-1])

[2 3]
[1 3 5]
[5 4 3 2 1]


In [56]:
# Array bidimensional

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print(array[0:2, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
