# Pandas
Biblioteca python que interage com tabelas(DataFrames)

In [3]:
import pandas as pd 
import numpy as np

## Series

Resumidamente, transformar uma lista em uma seria pandas permite uma visão indexada dos dados.

In [4]:
lista = [12, 15 , 23, 34, 12, 87, 2]

pd.Series(lista)

0    12
1    15
2    23
3    34
4    12
5    87
6     2
dtype: int64

In [9]:
array = np.array(lista)
array


array([12, 15, 23, 34, 12, 87,  2])

In [10]:
array_serie = pd.Series(array)
array_serie

0    12
1    15
2    23
3    34
4    12
5    87
6     2
dtype: int64

professor: A série deve usar sempre uma mesma tipagem de dados.

mas abaixo  vemos que é possível atribuir um inteiro

In [24]:
lista = ['a', 'b', 'c', 'd', 1,  5., 'a', True]
serie_str = pd.Series(lista)
#type(serie_str[2])
serie_str

0       a
1       b
2       c
3       d
4       1
5     5.0
6       a
7    True
dtype: object

In [25]:
serie_str.describe()

count     8
unique    6
top       a
freq      2
dtype: object

In [26]:
# O python aceita, porém talvez não deva ser feito
serie_doida = pd.Series(['a', 'b', 'c', 'd', 1,  5., 'a', True])

In [28]:
# Criando séries apartir de dicionários

dicionario = {"tomate": 3.5, "agua": 1.9, "coca": 10.9}

serie_dicionario = pd.Series(dicionario)
serie_dicionario

tomate     3.5
agua       1.9
coca      10.9
dtype: float64

Como já visto, em dicionário que é uma estrutura de chave e valor, temos diversos meios de acessar seus elementos

In [30]:
dicionario.keys()

dict_keys(['tomate', 'agua', 'coca'])

In [32]:
dicionario.values()

3.5

Com series pandas também podemos acessar os valores, porém, o retorno será um array.

In [38]:
print(serie_dicionario.values)
print('='*50)
print(serie_dicionario.keys)

[ 3.5  1.9 10.9]
<bound method Series.keys of tomate     3.5
agua       1.9
coca      10.9
dtype: float64>


In [39]:
# INDEX
serie_dicionario.index

Index(['tomate', 'agua', 'coca'], dtype='object')

### INDEXAÇÃO

In [40]:
# ainda pode ser feito, mas gera um warning. tratar com ILOC
serie_dicionario[0]

/tmp/ipykernel_35883/1769963325.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie_dicionario[0]


np.float64(3.5)

In [42]:
# Porém não aceita indices negativos
# Mas por algum motivo agora funcionou, mas não deve ser feito. 
print(serie_dicionario[-1])

10.9


/tmp/ipykernel_35883/1101357398.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(serie_dicionario[-1])


#### Slice

In [46]:
array_serie

0    12
1    15
2    23
3    34
4    12
5    87
6     2
dtype: int64

In [47]:
array_serie[1:5]

1    15
2    23
3    34
4    12
dtype: int64

#### Labels

In [49]:
print(array_serie)

0    12
1    15
2    23
3    34
4    12
5    87
6     2
dtype: int64


In [51]:
# Posso dar nomes aos indices
lista_numeros = [1,2,3,4,5,6,7]
lista_index = ['a','b','c','d','e','f','g']

seria_indexada = pd.Series(index=lista_index, data=lista_numeros)

In [52]:
seria_indexada

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

### OPERAÇÕES MATEMÁTICAS

In [57]:
# aumentando os preços do dicionario
serie_dicionario + 10

tomate    13.5
agua      11.9
coca      20.9
dtype: float64

tudo que podia ser utilizado em um array pode ser utilizado em uma serie.

In [58]:
serie_dicionario * 10

tomate     35.0
agua       19.0
coca      109.0
dtype: float64

### Métodos do Pandas

In [68]:
notas = [3.4, 7.8, 2.3, 9.5, 4.7, 6.1, 8.3, 1.2, 5.6, 7.4, 2.9, 9.3, 4.5, 6.7, 8.9, 1.4, 5.2, 7.6, 2.4, 9.3, 4.1, 6.8, 8.3, 1.7, 5.8, 7.1,6.1, 2.6, 9.7]
serie_notas = pd.Series(notas)

In [61]:
serie_notas.describe()

count    28.000000
mean      5.732143
std       2.718531
min       1.200000
25%       3.275000
50%       5.950000
75%       7.925000
max       9.700000
dtype: float64

In [69]:
# Ordenar valores mantendo o indice original
serie_notas.sort_values()

7     1.2
15    1.4
23    1.7
2     2.3
18    2.4
27    2.6
10    2.9
0     3.4
20    4.1
12    4.5
4     4.7
16    5.2
8     5.6
24    5.8
5     6.1
26    6.1
13    6.7
21    6.8
25    7.1
9     7.4
17    7.6
1     7.8
22    8.3
6     8.3
14    8.9
11    9.3
19    9.3
3     9.5
28    9.7
dtype: float64

In [70]:
# Exibir valores únicos
serie_notas.unique()

array([3.4, 7.8, 2.3, 9.5, 4.7, 6.1, 8.3, 1.2, 5.6, 7.4, 2.9, 9.3, 4.5,
       6.7, 8.9, 1.4, 5.2, 7.6, 2.4, 4.1, 6.8, 1.7, 5.8, 7.1, 2.6, 9.7])

In [72]:
# Exibir a quantidade de valores únicos
serie_notas.nunique()

26

In [74]:
# Exibir a quantidade ordenada de cada elemento. 
serie_notas.value_counts()

8.3    2
6.1    2
9.3    2
7.8    1
9.5    1
3.4    1
4.7    1
1.2    1
5.6    1
2.3    1
7.4    1
2.9    1
4.5    1
6.7    1
8.9    1
1.4    1
5.2    1
7.6    1
2.4    1
4.1    1
6.8    1
1.7    1
5.8    1
7.1    1
2.6    1
9.7    1
Name: count, dtype: int64

In [75]:
# Exibir a quantidade ordenada de cada elemento em porcentagem. 
serie_notas.value_counts(normalize=True)

8.3    0.068966
6.1    0.068966
9.3    0.068966
7.8    0.034483
9.5    0.034483
3.4    0.034483
4.7    0.034483
1.2    0.034483
5.6    0.034483
2.3    0.034483
7.4    0.034483
2.9    0.034483
4.5    0.034483
6.7    0.034483
8.9    0.034483
1.4    0.034483
5.2    0.034483
7.6    0.034483
2.4    0.034483
4.1    0.034483
6.8    0.034483
1.7    0.034483
5.8    0.034483
7.1    0.034483
2.6    0.034483
9.7    0.034483
Name: proportion, dtype: float64

In [78]:
# exibir porcentagem
serie_notas.value_counts(normalize=True).mul(100).round(2)

8.3    6.90
6.1    6.90
9.3    6.90
7.8    3.45
9.5    3.45
3.4    3.45
4.7    3.45
1.2    3.45
5.6    3.45
2.3    3.45
7.4    3.45
2.9    3.45
4.5    3.45
6.7    3.45
8.9    3.45
1.4    3.45
5.2    3.45
7.6    3.45
2.4    3.45
4.1    3.45
6.8    3.45
1.7    3.45
5.8    3.45
7.1    3.45
2.6    3.45
9.7    3.45
Name: proportion, dtype: float64

In [79]:
# exibir porcentagem
serie_notas.value_counts(normalize=True).mul(100).round(2).astype(str) + " %"

8.3     6.9 %
6.1     6.9 %
9.3     6.9 %
7.8    3.45 %
9.5    3.45 %
3.4    3.45 %
4.7    3.45 %
1.2    3.45 %
5.6    3.45 %
2.3    3.45 %
7.4    3.45 %
2.9    3.45 %
4.5    3.45 %
6.7    3.45 %
8.9    3.45 %
1.4    3.45 %
5.2    3.45 %
7.6    3.45 %
2.4    3.45 %
4.1    3.45 %
6.8    3.45 %
1.7    3.45 %
5.8    3.45 %
7.1    3.45 %
2.6    3.45 %
9.7    3.45 %
Name: proportion, dtype: object

In [76]:
# Exibir a quantidade ordenada de cada elemento em porcentagem. 
serie_notas.value_counts(normalize=True, bins=5)

(1.191, 2.9]    0.241379
(8.0, 9.7]      0.241379
(4.6, 6.3]      0.206897
(6.3, 8.0]      0.206897
(2.9, 4.6]      0.103448
Name: proportion, dtype: float64

In [82]:
serie_notas.value_counts(normalize=True, bins=5).mul(100).round(2).astype(str) + " %"

(1.191, 2.9]    24.14 %
(8.0, 9.7]      24.14 %
(4.6, 6.3]      20.69 %
(6.3, 8.0]      20.69 %
(2.9, 4.6]      10.34 %
Name: proportion, dtype: object

In [83]:
serie_notas.sum()

np.float64(166.7)

In [84]:
serie_notas.mean()

np.float64(5.748275862068965)

In [85]:
serie_notas.min()

np.float64(1.2)

In [87]:
serie_notas.max()

np.float64(9.7)

In [88]:
serie_notas.std()

np.float64(2.6769679929853436)

In [89]:
serie_notas.median()

np.float64(6.1)

In [90]:
serie_notas.mode()

0    6.1
1    8.3
2    9.3
dtype: float64

In [91]:
serie_notas.quantile(0.25)

np.float64(3.4)

In [92]:
serie_notas.quantile(0.75)

np.float64(7.8)

In [94]:
serie_notas.quantile(0.1)

np.float64(2.18)

In [95]:
serie_notas.describe()

count    29.000000
mean      5.748276
std       2.676968
min       1.200000
25%       3.400000
50%       6.100000
75%       7.800000
max       9.700000
dtype: float64

In [96]:
serie_notas.describe(percentiles=np.arange(0, 0.9, 0.1))

count    29.000000
mean      5.748276
std       2.676968
min       1.200000
0%        1.200000
10%       2.180000
20%       2.780000
30%       4.260000
40%       5.280000
50%       6.100000
60%       6.780000
70%       7.520000
80%       8.300000
max       9.700000
dtype: float64

**2)** Considere uma série de notas de alunos:
 
 notas = pd.Series([10, 8, 6.5, 9, 7.5, 8.5, 9, 9, 4, 8.5, 7.5,
                   8, 10, 10, 4.5, 4.5, 9, 8, 8, 9, 9, 9, 6.5,
                   5, 6, 4.5, 9, 10, 1, 0,5, 7, 9, 6.5, 5, 8])
                   
Determine:

**a)** A nota média

**b)** O desvio padrão

**c)** A moda

**d)** A mediana

In [97]:
notas = pd.Series([10, 8, 6.5, 9, 7.5, 8.5, 9, 9, 4, 8.5, 7.5,
                   8, 10, 10, 4.5, 4.5, 9, 8, 8, 9, 9, 9, 6.5,
                   5, 6, 4.5, 9, 10, 1, 0,5, 7, 9, 6.5, 5, 8])

In [100]:
media = notas.mean().round(2)
print(f"Media: {media}")

Media: 7.19


In [110]:
desvio = notas.std().round(2)
print(f"Desvio Padrão: {desvio}")

Desvio Padrão: 2.43


In [111]:
moda = notas.mode().values[0].round(2)
print(f"Moda: {moda}")

Moda: 9.0


In [103]:
mediana = notas.median().round(2)
print(f"Mediana: {mediana}")

Mediana: 8.0


In [108]:
lista = [3.4, 7.8, 2.3, 9.5, 4.7, 6.1, 8.3, 1.2, 5.6, 7.4, 2.9, 9.0, 4.5, 6.7, 8.9, 1.4, 5.2, 7.6, 2.4, 9.3, 4.1, 6.8, 8.5, 1.7, 5.8, 7.1, 2.6, 9.7]

notas2 = pd.Series(lista)
notas2

0     3.4
1     7.8
2     2.3
3     9.5
4     4.7
5     6.1
6     8.3
7     1.2
8     5.6
9     7.4
10    2.9
11    9.0
12    4.5
13    6.7
14    8.9
15    1.4
16    5.2
17    7.6
18    2.4
19    9.3
20    4.1
21    6.8
22    8.5
23    1.7
24    5.8
25    7.1
26    2.6
27    9.7
dtype: float64

In [106]:
notas2.describe()

count    28.000000
mean      5.732143
std       2.718531
min       1.200000
25%       3.275000
50%       5.950000
75%       7.925000
max       9.700000
dtype: float64

In [109]:
notas2.nunique()

28

## DataFrame

In [113]:
df_notas = pd.DataFrame(notas)
df_notas

0
0   10.0
1    8.0
2    6.5
3    9.0
4    7.5
5    8.5
6    9.0
7    9.0
8    4.0
9    8.5
10   7.5
11   8.0
12  10.0
13  10.0
14   4.5
15   4.5
16   9.0
17   8.0
18   8.0
19   9.0
20   9.0
21   9.0
22   6.5
23   5.0
24   6.0
25   4.5
26   9.0
27  10.0
28   1.0
29   0.0
30   5.0
31   7.0
32   9.0
33   6.5
34   5.0
35   8.0

In [114]:
dictionary = {'Alunos': ['Sandro', 'Rafael', 'Tiago', 'André', 'Camila', 'Teo', 'Carlos', 'Juca', 'Carla'],
              'Notas': [8, 10, 9.5, 7.5, 9.5, 10, 5, 6.5, 10]}

In [116]:
df_dicionario = pd.DataFrame(dictionary)
df_dicionario.T

0       1      2      3       4     5       6     7      8
Alunos  Sandro  Rafael  Tiago  André  Camila   Teo  Carlos  Juca  Carla
Notas      8.0    10.0    9.5    7.5     9.5  10.0     5.0   6.5   10.0